#docker-compose-pg-only.yml
version: '3.8'
services:
  redis:
    container_name: rediscache
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  db:
    container_name: docustoragedb
    image: docustoragedb:dev
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  services:
    container_name: docustorageui
    build:
      context: ./
      target: dev
    image: docustorageui:dev
    depends_on:
      - webapi
    ports:
      - 3000:3000
    links:
      - webapi
    volumes:
      - './:/src'    
  webapi:
    container_name: docustorage
    build:
      context: ./
      target: dev
    image: docustorage:dev
    depends_on:
      - db
      - redis
    ports:
      - 4000:80
    environment:
      NODE_ENV: dev
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local